In [1]:
import numpy as np

In [2]:
numbers = np.array([1,2,3,4,5])

In [3]:
numbers


array([1, 2, 3, 4, 5])

In [4]:
num2 = numbers[0:4]

In [5]:
num2

array([1, 2, 3, 4])

In [6]:
numbers.cumsum()

array([ 1,  3,  6, 10, 15])